#!/bin/bash
# pretrain
MAIN_PATH=../adapter-transformers/examples/my
cd ${MAIN_PATH}
GLUE_DIR=${MAIN_PATH}/glue_data
TASK_NAME=QQP
# /home/users/nus/dcshanw/miniconda3/envs/cqa/bin/msra_qr  SST-2 MRPC STS-B 

for iter1 in "2000" "3000" "4000" "5000" "6000" "7000" "8000" "9000" "10000"
do
echo ${iter1}
CUDA_VISIBLE_DEVICES=0 python ../adapter-transformers/examples/text-classification/run_glue_alt.py  \
  --model_name_or_path  bert-base-uncased \
  --task_name $TASK_NAME \
  --data_dir $GLUE_DIR/$TASK_NAME \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 1e-4 \
  --num_train_epochs 50 \
  --evaluation_strategy 'steps' \
  --overwrite_output_dir \
  --save_total_limit 20 \
  --output_dir temp_finetune_${TASK_NAME}/${TASK_NAME}_${iter1}  \
  --train_adapter \
  --load_adapter temp_adp_mlm_${TASK_NAME}/checkpoint-105000/task_checkpoint_file  \
  --adapter_config houlsby   

done

# --load_adapter: checkpoint file generated by with_adapter_pretrain.sh
